package ca.jent.payload;

import java.util.Arrays;
import java.util.Collections;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * This comes from executing: Locale.getISOCountries()
 * The outcome has been formatted (manually) to enum below.
 *
 * Note: The String countryName should never be used within the CORE of the µservice (bounded context) but should
 *       be used only when downstream incoming payload uses the full country name and we need to map that country
 *       name to our enum. (See public static final Map<String, Country> COUNTRIES at the bottom.
 */
public enum Country {
    NI("Nicaragua"),
    NG("Nigeria"),
    NF("Norfolk Island"),
    NE("Niger"),
    NC("New Caledonia"),
    NA("Namibia"),
    MZ("Mozambique"),
    MY("Malaysia"),
    MX("Mexico"),
    MW("Malawi"),
    MV("Maldives"),
    MU("Mauritius"),
    MT("Malta"),
    MS("Montserrat"),
    MR("Mauritania"),
    MQ("Martinique"),
    MP("Northern Mariana Islands"),
    MO("Macao SAR China"),
    MN("Mongolia"),
    MM("Myanmar (Burma)"),
    ML("Mali"),
    MK("North Macedonia"),
    MH("Marshall Islands"),
    MG("Madagascar"),
    MF("St. Martin"),
    ME("Montenegro"),
    MD("Moldova"),
    MC("Monaco"),
    MA("Morocco"),
    LY("Libya"),
    LV("Latvia"),
    LU("Luxembourg"),
    LT("Lithuania"),
    LS("Lesotho"),
    LR("Liberia"),
    LK("Sri Lanka"),
    LI("Liechtenstein"),
    LC("St. Lucia"),
    LB("Lebanon"),
    LA("Laos"),
    KZ("Kazakhstan"),
    KY("Cayman Islands"),
    KW("Kuwait"),
    KR("South Korea"),
    KP("North Korea"),
    KN("St. Kitts & Nevis"),
    KM("Comoros"),
    KI("Kiribati"),
    KH("Cambodia"),
    KG("Kyrgyzstan"),
    KE("Kenya"),
    ZW("Zimbabwe"),
    JP("Japan"),
    JO("Jordan"),
    JM("Jamaica"),
    ZM("Zambia"),
    JE("Jersey"),
    ZA("South Africa"),
    IT("Italy"),
    IS("Iceland"),
    IR("Iran"),
    YT("Mayotte"),
    IQ("Iraq"),
    IO("British Indian Ocean Territory"),
    IN("India"),
    IM("Isle of Man"),
    IL("Israel"),
    IE("Ireland"),
    ID("Indonesia"),
    YE("Yemen"),
    HU("Hungary"),
    HT("Haiti"),
    HR("Croatia"),
    HN("Honduras"),
    HM("Heard & McDonald Islands"),
    HK("Hong Kong SAR China"),
    GY("Guyana"),
    GW("Guinea-Bissau"),
    GU("Guam"),
    GT("Guatemala"),
    GS("South Georgia & South Sandwich Islands"),
    GR("Greece"),
    GQ("Equatorial Guinea"),
    WS("Samoa"),
    GP("Guadeloupe"),
    GN("Guinea"),
    GM("Gambia"),
    GL("Greenland"),
    GI("Gibraltar"),
    GH("Ghana"),
    GG("Guernsey"),
    GF("French Guiana"),
    GE("Georgia"),
    GD("Grenada"),
    WF("Wallis & Futuna"),
    GB("United Kingdom"),
    GA("Gabon"),
    VU("Vanuatu"),
    FR("France"),
    FO("Faroe Islands"),
    FM("Micronesia"),
    VN("Vietnam"),
    FK("Falkland Islands"),
    FJ("Fiji"),
    FI("Finland"),
    VI("US Virgin Islands"),
    VG("British Virgin Islands"),
    VE("Venezuela"),
    VC("St. Vincent & Grenadines"),
    VA("Vatican City"),
    UZ("Uzbekistan"),
    UY("Uruguay"),
    ET("Ethiopia"),
    ES("Spain"),
    ER("Eritrea"),
    US("United States"),
    UM("US Outlying Islands"),
    EH("Western Sahara"),
    EG("Egypt"),
    EE("Estonia"),
    UG("Uganda"),
    EC("Ecuador"),
    UA("Ukraine"),
    DZ("Algeria"),
    DO("Dominican Republic"),
    DM("Dominica"),
    DK("Denmark"),
    TZ("Tanzania"),
    DJ("Djibouti"),
    TW("Taiwan"),
    TV("Tuvalu"),
    DE("Germany"),
    TT("Trinidad & Tobago"),
    TR("Turkey"),
    TO("Tonga"),
    TN("Tunisia"),
    TM("Turkmenistan"),
    TL("Timor-Leste"),
    TK("Tokelau"),
    CZ("Czechia"),
    TJ("Tajikistan"),
    CY("Cyprus"),
    CX("Christmas Island"),
    TH("Thailand"),
    CW("Curaçao"),
    TG("Togo"),
    CV("Cape Verde"),
    TF("French Southern Territories"),
    CU("Cuba"),
    TD("Chad"),
    TC("Turks & Caicos Islands"),
    CR("Costa Rica"),
    CO("Colombia"),
    CN("China"),
    CM("Cameroon"),
    CL("Chile"),
    CK("Cook Islands"),
    SZ("Eswatini"),
    SY("Syria"),
    CI("Côte d’Ivoire"),
    SX("Sint Maarten"),
    CH("Switzerland"),
    CG("Congo - Brazzaville"),
    SV("El Salvador"),
    CF("Central African Republic"),
    ST("São Tomé & Príncipe"),
    SS("South Sudan"),
    SR("Suriname"),
    CD("Congo - Kinshasa"),
    CC("Cocos (Keeling) Islands"),
    SO("Somalia"),
    SN("Senegal"),
    SM("San Marino"),
    SL("Sierra Leone"),
    SK("Slovakia"),
    SJ("Svalbard & Jan Mayen"),
    SI("Slovenia"),
    SH("St. Helena"),
    SG("Singapore"),
    CA("Canada"),
    SE("Sweden"),
    SD("Sudan"),
    SC("Seychelles"),
    SB("Solomon Islands"),
    SA("Saudi Arabia"),
    BZ("Belize"),
    BY("Belarus"),
    BW("Botswana"),
    BV("Bouvet Island"),
    BT("Bhutan"),
    BS("Bahamas"),
    RW("Rwanda"),
    BR("Brazil"),
    RU("Russia"),
    BQ("Caribbean Netherlands"),
    RS("Serbia"),
    BO("Bolivia"),
    BN("Brunei"),
    BM("Bermuda"),
    RO("Romania"),
    BL("St. Barthélemy"),
    BJ("Benin"),
    BI("Burundi"),
    BH("Bahrain"),
    BG("Bulgaria"),
    BF("Burkina Faso"),
    BE("Belgium"),
    BD("Bangladesh"),
    RE("Réunion"),
    BB("Barbados"),
    BA("Bosnia & Herzegovina"),
    AZ("Azerbaijan"),
    AX("Åland Islands"),
    AW("Aruba"),
    AU("Australia"),
    AT("Austria"),
    AS("American Samoa"),
    AR("Argentina"),
    AQ("Antarctica"),
    AO("Angola"),
    AM("Armenia"),
    AL("Albania"),
    AI("Anguilla"),
    AG("Antigua & Barbuda"),
    AF("Afghanistan"),
    AE("United Arab Emirates"),
    AD("Andorra"),
    QA("Qatar"),
    PY("Paraguay"),
    PW("Palau"),
    PT("Portugal"),
    PS("Palestinian Territories"),
    PR("Puerto Rico"),
    PN("Pitcairn Islands"),
    PM("St. Pierre & Miquelon"),
    PL("Poland"),
    PK("Pakistan"),
    PH("Philippines"),
    PG("Papua New Guinea"),
    PF("French Polynesia"),
    PE("Peru"),
    PA("Panama"),
    OM("Oman"),
    NZ("New Zealand"),
    NU("Niue"),
    NR("Nauru"),
    NP("Nepal"),
    NO("Norway"),
    NL("Netherlands");

    private final String countryFullName;

    Country(String countryName) {
        this.countryFullName = countryName;
    }

    String getCountryFullName() {
        return countryFullName;
    }

    /**
     * Should only be used when a downstream incoming payload give us the country full name and need to map it to our enum.
     */
    public static final Map<String, Country> COUNTRIES = Arrays.stream(Country.values()).collect(Collectors.toUnmodifiableMap(
        Country::getCountryFullName,
        Function.identity()
    ));
}
